apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: message-api
  name: message-api
  namespace: message-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: message-api
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: message-api
    spec:
      hostAliases:
        - ip: 10.170.6.24
          hostnames:
            - im01
        - ip: 10.170.6.25
          hostnames:
            - im02
        - ip: 10.170.6.26
          hostnames:
            - im03
      imagePullSecrets:
        - name: qtech-docker-login-registry  # 提前在项目下配置访问阿里云的账号密码
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/qtech/message-api:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: Default  # Default表示使用宿主机的DNS设置
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-api
  name: message-api
  namespace: message-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: message-api
  sessionAffinity: None
  type: ClusterIP

