logging:
  config: classpath:logback-spring.xml
  level:
    root: info

#AWS S3配置
aws:
  s3:
    accessKey: 3N9CP0C0D0VNY5UFLACJ
    secretKey: jAkyxAwskyg0rQ5U27BZ3PcphtmVbiLiAjkXylUn
    region: us-east-1
    endpoint: http://rook-ceph-rgw-my-store-external.rook-ceph
    bucket:  default