server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 20

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

hdfs:
  hdfsPath: hdfs://cluster
  hadoopUser: qtech