server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 20

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info

ceph:
  accessKey: 3N9CP0C0D0VNY5UFLACJ
  secretKey: jAkyxAwskyg0rQ5U27BZ3PcphtmVbiLiAjkXylUn
  region: us-east-1
  endpoint: http://10.170.6.40:31033
