#AWS S3配置
aws:
  s3:
    accessKey: 9OQ1CKI8DCJIYTB2Y7H0
    secretKey: MArlxB1h71FsGY8KHhxximDdkBaOulIzAzBTUvy7
    region: us-east-1
    endpoint: http://rook-ceph-rgw-my-store-external.rook-ceph
    bucket:  default