server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 20

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

hdfs:
  hdfsPath: hdfs://cluster
  hadoopUser: qtech

logging:
  # 若不配置，默认使用 ##logback-spring.xml，logback-udf.xml不能命名为 logback-spring.xml，logback.xml的加载早于application.yml配置文件，在logback.xml中使用<springProperty>标签来获取配置文件中的变量值，读取不到而报出错误信息。
  config: classpath:logback-spring.xml