server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 10

logging:
  level:
    root: info
    com.qtech.olp: debug
    org.springframework.web: debug
    io.lettuce.core: debug
    org.springframework.data.redis: debug
    com.qtech.olp.config.druid: debug
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #redis配置信息
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器连接密码（默认为空）
    password: im@2024
    ## 连接超时时间（毫秒）
    timeout: 5000
    ## 集群配置
    cluster:
      ### 集群中所有节点
      nodes:
        - 10.170.6.24:6379
        - 10.170.6.25:6379
        - 10.170.6.26:6379
        - 10.170.6.141:6379
        - 10.170.6.142:6379
      ### 最大重定向数，最好为集群节点数，比如第一台挂了，连第二台，第二台挂了连第三台，这个是重新连接的最大数量
      max-redirects: 6
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 1
      ## 集群配置
      cluster:
        refresh:
          # 支持集群拓扑动态感应刷新,自适应拓扑刷新是否使用所有可用的更新，默认false关闭，类似nacos定时刷新服务列表
          adaptive: true
          # 定时刷新时间 毫秒
          period: 2000

  kafka:
    bootstrap-servers:
    - 10.170.6.24:9092
    - 10.170.6.25:9092
    - 10.170.6.26:9092
    consumer:
      group-id: aaList
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      client-id: aaList
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
