# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      # Linux每个进程中的线程数不允许超过1000
      max: 900
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 200

spring:
  kafka:
    bootstrap-servers:
      - 10.170.6.24:9092
      - 10.170.6.25:9092
      - 10.170.6.26:9092
    producer:
      client-id: aaList
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

springdoc:
  api-docs:
    enabled: true
  openapi:
    info:
      title: message-api
      description: message-api
      version: 1.0.0
      contact: gaoolin@gmail.com

logging:
  level:
    root: info

api:
  keys:
    admin: cde456
    user: abc123


exempt:
  paths:
    - /message/api/list/send

