server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1300
    threads:
      max: 1000
      min-spare: 20
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.qtech.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

