# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      first:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//10.170.6.144:1521/qtechIm
        username: imBiz
        password: M5F5JkfnQ
      # 从库数据源
      second:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.170.6.40:32333/qtech_eq_dwd?useServerPrepStmts=false&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password:

      # 连接池配置
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      # Druid 监控配置
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: qtech
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  kafka:
    streams:
      bootstrap-servers:
        - 10.170.6.24:9092
        - 10.170.6.25:9092
        - 10.170.6.26:9092
      application-id: deduplication-application
      cache-max-size-buffering: 536870912  # 512MB
      state-dir: /tmp/kafka-streams
    store:
      name: deduplication-store

  rabbitmq:
    host: 10.170.6.40
    port: 31131
    username: qtech
    password: Ee786549

logging:
  level:
    root: info
    org.mybatis.spring: DEBUG
    org.apache.ibatis: DEBUG
    com.qtech.mq.mapper: DEBUG