# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      first:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//10.170.6.144:1521/qtechIm
        username: imBiz
        password: M5F5JkfnQ
      # 从库数据源
      second:
        url: jdbc:mysql://10.170.6.40:32333/qtech_eq_dwd?useServerPrepStmts=false&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password:

      # 连接池配置
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      # Druid 监控配置
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: qtech
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  #redis配置信息
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器连接密码（默认为空）
    password: im@2024
    ## 连接超时时间（毫秒）
    timeout: 5000
    ## 集群配置
    cluster:
      ### 集群中所有节点
      nodes:
        - 10.170.6.24:6379
        - 10.170.6.25:6379
        - 10.170.6.26:6379
        - 10.170.6.141:6379
        - 10.170.6.142:6379
        - 10.170.1.68:6379
      ### 最大重定向数，最好为集群节点数，比如第一台挂了，连第二台，第二台挂了连第三台，这个是重新连接的最大数量
      max-redirects: 3
    lettuce:
      read-from: REPLICA_PREFERRED # 配置从节点优先读
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 5
      ## 集群配置
      cluster:
        refresh:
          # 支持集群拓扑动态感应刷新,自适应拓扑刷新是否使用所有可用的更新，默认false关闭，类似nacos定时刷新服务列表
          adaptive: true
          # 定时刷新时间 毫秒
          period: 2000

  kafka:
    bootstrap-servers:
      - 10.170.6.24:9092
      - 10.170.6.25:9092
      - 10.170.6.26:9092
    consumer:
      group-id: im-group
#      auto-offset-reset: earliest

  rabbitmq:
    host: 10.170.6.40
    port: 31131
    username: qtech
    password: Ee786549

logging:
  level:
    root: info
#    org.mybatis.spring: DEBUG
#    org.apache.ibatis: DEBUG
    com.qtech.mq.mapper: DEBUG