/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.qtech.mq.serializer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CompositeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4547726483560328175L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CompositeKey\",\"namespace\":\"com.qtech.mq.serializer\",\"fields\":[{\"name\":\"simId\",\"type\":\"string\"},{\"name\":\"prodType\",\"type\":\"string\"},{\"name\":\"chkDt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CompositeKey> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CompositeKey> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CompositeKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CompositeKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CompositeKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CompositeKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CompositeKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CompositeKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CompositeKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence simId;
  private java.lang.CharSequence prodType;
  private java.lang.CharSequence chkDt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CompositeKey() {}

  /**
   * All-args constructor.
   * @param simId The new value for simId
   * @param prodType The new value for prodType
   * @param chkDt The new value for chkDt
   */
  public CompositeKey(java.lang.CharSequence simId, java.lang.CharSequence prodType, java.lang.CharSequence chkDt) {
    this.simId = simId;
    this.prodType = prodType;
    this.chkDt = chkDt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return simId;
    case 1: return prodType;
    case 2: return chkDt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: simId = (java.lang.CharSequence)value$; break;
    case 1: prodType = (java.lang.CharSequence)value$; break;
    case 2: chkDt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'simId' field.
   * @return The value of the 'simId' field.
   */
  public java.lang.CharSequence getSimId() {
    return simId;
  }


  /**
   * Sets the value of the 'simId' field.
   * @param value the value to set.
   */
  public void setSimId(java.lang.CharSequence value) {
    this.simId = value;
  }

  /**
   * Gets the value of the 'prodType' field.
   * @return The value of the 'prodType' field.
   */
  public java.lang.CharSequence getProdType() {
    return prodType;
  }


  /**
   * Sets the value of the 'prodType' field.
   * @param value the value to set.
   */
  public void setProdType(java.lang.CharSequence value) {
    this.prodType = value;
  }

  /**
   * Gets the value of the 'chkDt' field.
   * @return The value of the 'chkDt' field.
   */
  public java.lang.CharSequence getChkDt() {
    return chkDt;
  }


  /**
   * Sets the value of the 'chkDt' field.
   * @param value the value to set.
   */
  public void setChkDt(java.lang.CharSequence value) {
    this.chkDt = value;
  }

  /**
   * Creates a new CompositeKey RecordBuilder.
   * @return A new CompositeKey RecordBuilder
   */
  public static com.qtech.mq.serializer.CompositeKey.Builder newBuilder() {
    return new com.qtech.mq.serializer.CompositeKey.Builder();
  }

  /**
   * Creates a new CompositeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CompositeKey RecordBuilder
   */
  public static com.qtech.mq.serializer.CompositeKey.Builder newBuilder(com.qtech.mq.serializer.CompositeKey.Builder other) {
    if (other == null) {
      return new com.qtech.mq.serializer.CompositeKey.Builder();
    } else {
      return new com.qtech.mq.serializer.CompositeKey.Builder(other);
    }
  }

  /**
   * Creates a new CompositeKey RecordBuilder by copying an existing CompositeKey instance.
   * @param other The existing instance to copy.
   * @return A new CompositeKey RecordBuilder
   */
  public static com.qtech.mq.serializer.CompositeKey.Builder newBuilder(com.qtech.mq.serializer.CompositeKey other) {
    if (other == null) {
      return new com.qtech.mq.serializer.CompositeKey.Builder();
    } else {
      return new com.qtech.mq.serializer.CompositeKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for CompositeKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CompositeKey>
    implements org.apache.avro.data.RecordBuilder<CompositeKey> {

    private java.lang.CharSequence simId;
    private java.lang.CharSequence prodType;
    private java.lang.CharSequence chkDt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.qtech.mq.serializer.CompositeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.simId)) {
        this.simId = data().deepCopy(fields()[0].schema(), other.simId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.prodType)) {
        this.prodType = data().deepCopy(fields()[1].schema(), other.prodType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.chkDt)) {
        this.chkDt = data().deepCopy(fields()[2].schema(), other.chkDt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CompositeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.qtech.mq.serializer.CompositeKey other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.simId)) {
        this.simId = data().deepCopy(fields()[0].schema(), other.simId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.prodType)) {
        this.prodType = data().deepCopy(fields()[1].schema(), other.prodType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.chkDt)) {
        this.chkDt = data().deepCopy(fields()[2].schema(), other.chkDt);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'simId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSimId() {
      return simId;
    }


    /**
      * Sets the value of the 'simId' field.
      * @param value The value of 'simId'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.CompositeKey.Builder setSimId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.simId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'simId' field has been set.
      * @return True if the 'simId' field has been set, false otherwise.
      */
    public boolean hasSimId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'simId' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.CompositeKey.Builder clearSimId() {
      simId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'prodType' field.
      * @return The value.
      */
    public java.lang.CharSequence getProdType() {
      return prodType;
    }


    /**
      * Sets the value of the 'prodType' field.
      * @param value The value of 'prodType'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.CompositeKey.Builder setProdType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.prodType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'prodType' field has been set.
      * @return True if the 'prodType' field has been set, false otherwise.
      */
    public boolean hasProdType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'prodType' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.CompositeKey.Builder clearProdType() {
      prodType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'chkDt' field.
      * @return The value.
      */
    public java.lang.CharSequence getChkDt() {
      return chkDt;
    }


    /**
      * Sets the value of the 'chkDt' field.
      * @param value The value of 'chkDt'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.CompositeKey.Builder setChkDt(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.chkDt = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'chkDt' field has been set.
      * @return True if the 'chkDt' field has been set, false otherwise.
      */
    public boolean hasChkDt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'chkDt' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.CompositeKey.Builder clearChkDt() {
      chkDt = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CompositeKey build() {
      try {
        CompositeKey record = new CompositeKey();
        record.simId = fieldSetFlags()[0] ? this.simId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.prodType = fieldSetFlags()[1] ? this.prodType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.chkDt = fieldSetFlags()[2] ? this.chkDt : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CompositeKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<CompositeKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CompositeKey>
    READER$ = (org.apache.avro.io.DatumReader<CompositeKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.simId);

    out.writeString(this.prodType);

    out.writeString(this.chkDt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.simId = in.readString(this.simId instanceof Utf8 ? (Utf8)this.simId : null);

      this.prodType = in.readString(this.prodType instanceof Utf8 ? (Utf8)this.prodType : null);

      this.chkDt = in.readString(this.chkDt instanceof Utf8 ? (Utf8)this.chkDt : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.simId = in.readString(this.simId instanceof Utf8 ? (Utf8)this.simId : null);
          break;

        case 1:
          this.prodType = in.readString(this.prodType instanceof Utf8 ? (Utf8)this.prodType : null);
          break;

        case 2:
          this.chkDt = in.readString(this.chkDt instanceof Utf8 ? (Utf8)this.chkDt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










