/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.qtech.mq.serializer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7806703646943637014L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Record\",\"namespace\":\"com.qtech.mq.serializer\",\"fields\":[{\"name\":\"simId\",\"type\":\"string\"},{\"name\":\"prodType\",\"type\":\"string\"},{\"name\":\"chkDt\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Record> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Record> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Record> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Record> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Record> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Record to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Record from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Record instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Record fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence simId;
  private java.lang.CharSequence prodType;
  private java.lang.CharSequence chkDt;
  private java.lang.CharSequence code;
  private java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Record() {}

  /**
   * All-args constructor.
   * @param simId The new value for simId
   * @param prodType The new value for prodType
   * @param chkDt The new value for chkDt
   * @param code The new value for code
   * @param description The new value for description
   */
  public Record(java.lang.CharSequence simId, java.lang.CharSequence prodType, java.lang.CharSequence chkDt, java.lang.CharSequence code, java.lang.CharSequence description) {
    this.simId = simId;
    this.prodType = prodType;
    this.chkDt = chkDt;
    this.code = code;
    this.description = description;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return simId;
    case 1: return prodType;
    case 2: return chkDt;
    case 3: return code;
    case 4: return description;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: simId = (java.lang.CharSequence)value$; break;
    case 1: prodType = (java.lang.CharSequence)value$; break;
    case 2: chkDt = (java.lang.CharSequence)value$; break;
    case 3: code = (java.lang.CharSequence)value$; break;
    case 4: description = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'simId' field.
   * @return The value of the 'simId' field.
   */
  public java.lang.CharSequence getSimId() {
    return simId;
  }


  /**
   * Sets the value of the 'simId' field.
   * @param value the value to set.
   */
  public void setSimId(java.lang.CharSequence value) {
    this.simId = value;
  }

  /**
   * Gets the value of the 'prodType' field.
   * @return The value of the 'prodType' field.
   */
  public java.lang.CharSequence getProdType() {
    return prodType;
  }


  /**
   * Sets the value of the 'prodType' field.
   * @param value the value to set.
   */
  public void setProdType(java.lang.CharSequence value) {
    this.prodType = value;
  }

  /**
   * Gets the value of the 'chkDt' field.
   * @return The value of the 'chkDt' field.
   */
  public java.lang.CharSequence getChkDt() {
    return chkDt;
  }


  /**
   * Sets the value of the 'chkDt' field.
   * @param value the value to set.
   */
  public void setChkDt(java.lang.CharSequence value) {
    this.chkDt = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Creates a new Record RecordBuilder.
   * @return A new Record RecordBuilder
   */
  public static com.qtech.mq.serializer.Record.Builder newBuilder() {
    return new com.qtech.mq.serializer.Record.Builder();
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Record RecordBuilder
   */
  public static com.qtech.mq.serializer.Record.Builder newBuilder(com.qtech.mq.serializer.Record.Builder other) {
    if (other == null) {
      return new com.qtech.mq.serializer.Record.Builder();
    } else {
      return new com.qtech.mq.serializer.Record.Builder(other);
    }
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Record instance.
   * @param other The existing instance to copy.
   * @return A new Record RecordBuilder
   */
  public static com.qtech.mq.serializer.Record.Builder newBuilder(com.qtech.mq.serializer.Record other) {
    if (other == null) {
      return new com.qtech.mq.serializer.Record.Builder();
    } else {
      return new com.qtech.mq.serializer.Record.Builder(other);
    }
  }

  /**
   * RecordBuilder for Record instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Record>
    implements org.apache.avro.data.RecordBuilder<Record> {

    private java.lang.CharSequence simId;
    private java.lang.CharSequence prodType;
    private java.lang.CharSequence chkDt;
    private java.lang.CharSequence code;
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.qtech.mq.serializer.Record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.simId)) {
        this.simId = data().deepCopy(fields()[0].schema(), other.simId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.prodType)) {
        this.prodType = data().deepCopy(fields()[1].schema(), other.prodType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.chkDt)) {
        this.chkDt = data().deepCopy(fields()[2].schema(), other.chkDt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.code)) {
        this.code = data().deepCopy(fields()[3].schema(), other.code);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Record instance
     * @param other The existing instance to copy.
     */
    private Builder(com.qtech.mq.serializer.Record other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.simId)) {
        this.simId = data().deepCopy(fields()[0].schema(), other.simId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.prodType)) {
        this.prodType = data().deepCopy(fields()[1].schema(), other.prodType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.chkDt)) {
        this.chkDt = data().deepCopy(fields()[2].schema(), other.chkDt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.code)) {
        this.code = data().deepCopy(fields()[3].schema(), other.code);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'simId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSimId() {
      return simId;
    }


    /**
      * Sets the value of the 'simId' field.
      * @param value The value of 'simId'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder setSimId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.simId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'simId' field has been set.
      * @return True if the 'simId' field has been set, false otherwise.
      */
    public boolean hasSimId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'simId' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder clearSimId() {
      simId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'prodType' field.
      * @return The value.
      */
    public java.lang.CharSequence getProdType() {
      return prodType;
    }


    /**
      * Sets the value of the 'prodType' field.
      * @param value The value of 'prodType'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder setProdType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.prodType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'prodType' field has been set.
      * @return True if the 'prodType' field has been set, false otherwise.
      */
    public boolean hasProdType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'prodType' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder clearProdType() {
      prodType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'chkDt' field.
      * @return The value.
      */
    public java.lang.CharSequence getChkDt() {
      return chkDt;
    }


    /**
      * Sets the value of the 'chkDt' field.
      * @param value The value of 'chkDt'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder setChkDt(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.chkDt = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'chkDt' field has been set.
      * @return True if the 'chkDt' field has been set, false otherwise.
      */
    public boolean hasChkDt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'chkDt' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder clearChkDt() {
      chkDt = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.code = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder clearCode() {
      code = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.description = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.qtech.mq.serializer.Record.Builder clearDescription() {
      description = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Record build() {
      try {
        Record record = new Record();
        record.simId = fieldSetFlags()[0] ? this.simId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.prodType = fieldSetFlags()[1] ? this.prodType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.chkDt = fieldSetFlags()[2] ? this.chkDt : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.code = fieldSetFlags()[3] ? this.code : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.description = fieldSetFlags()[4] ? this.description : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Record>
    WRITER$ = (org.apache.avro.io.DatumWriter<Record>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Record>
    READER$ = (org.apache.avro.io.DatumReader<Record>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.simId);

    out.writeString(this.prodType);

    out.writeString(this.chkDt);

    out.writeString(this.code);

    out.writeString(this.description);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.simId = in.readString(this.simId instanceof Utf8 ? (Utf8)this.simId : null);

      this.prodType = in.readString(this.prodType instanceof Utf8 ? (Utf8)this.prodType : null);

      this.chkDt = in.readString(this.chkDt instanceof Utf8 ? (Utf8)this.chkDt : null);

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.simId = in.readString(this.simId instanceof Utf8 ? (Utf8)this.simId : null);
          break;

        case 1:
          this.prodType = in.readString(this.prodType instanceof Utf8 ? (Utf8)this.prodType : null);
          break;

        case 2:
          this.chkDt = in.readString(this.chkDt instanceof Utf8 ? (Utf8)this.chkDt : null);
          break;

        case 3:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 4:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










